---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vocational-test-ingress
  labels:
    app: vocational-test
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`vocational-test.ikigais.app`)
    kind: Rule
    services:
    - name: vocational-test-service
      port: 8000
      weight: 1
  - match: PathPrefix(`/health`)
    kind: Rule
    services:
    - name: vocational-test-service
      port: 8000
      weight: 1
---