---
apiVersion: v1
kind: Service
metadata:
  name: vocational-test-service
  labels:
    app: vocational-test
spec:
  type: ClusterIP
  selector:
    app: vocational-test
  ports:
  - name: http
    port: 8000
    targetPort: 8000
---